# Generated by Django 5.1.7 on 2025-04-16 11:43

import django.db.models.deletion
import profile.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    models.ImageField(upload_to=profile.models.upload_avatar_profile),
                ),
                (
                    "alt",
                    models.CharField(
                        default="avatar", max_length=12, verbose_name="Alt Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Avatar",
                "verbose_name_plural": "Avatars",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("fullName", models.CharField(blank=True, max_length=128, null=True)),
                ("phone", models.CharField(blank=True, max_length=12, null=True)),
                ("email", models.EmailField(blank=True, max_length=128, null=True)),
                (
                    "avatar",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_link",
                        to="profile.avatar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
        migrations.AddField(
            model_name="avatar",
            name="user_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avatar_link",
                to="profile.profile",
            ),
        ),
    ]
