# Generated by Django 5.1.7 on 2025-03-27 21:40

import django.core.validators
import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    models.ImageField(
                        upload_to=product.models.upload_product_preview,
                        verbose_name="Link",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        default="product_preview",
                        max_length=12,
                        verbose_name="Alt product image",
                    ),
                ),
            ],
            options={
                "verbose_name": "ProductImages",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("text", models.TextField(max_length=250)),
                (
                    "rate",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(5)],
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
            },
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("value", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Specification",
                "verbose_name_plural": "Specifications",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("description", models.TextField(max_length=50)),
                ("fullDescription", models.TextField(max_length=250)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("count", models.IntegerField(default=0)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("freeDelivery", models.BooleanField(default=False)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=2),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.category",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.subcategory",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="tags.tag")),
                (
                    "images",
                    models.ManyToManyField(blank=True, to="product.productimages"),
                ),
            ],
        ),
    ]
