# Generated by Django 5.1.7 on 2025-03-27 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profile.profile"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="reviews",
            field=models.ManyToManyField(blank=True, to="product.review"),
        ),
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.ManyToManyField(blank=True, to="product.specification"),
        ),
    ]
