# Generated by Django 5.1.7 on 2025-03-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.CharField(max_length=100, verbose_name="Автор"),
        ),
    ]
