# Generated by Django 5.1.7 on 2025-04-18 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                default="0",
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator("0"),
                    django.core.validators.MaxValueValidator("5"),
                ],
            ),
        ),
    ]
