# Generated by Django 5.1.7 on 2025-04-18 21:05

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("1"))],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                default="0",
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("5")),
                ],
            ),
        ),
    ]
