# Generated by Django 5.1.7 on 2025-04-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_product_price_alter_product_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["id"]},
        ),
    ]
