# Generated by Django 5.1.7 on 2025-04-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(max_length=16)),
                ("valid_period", models.CharField(max_length=15)),
                ("success", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("deliveryType", models.CharField(default="free", max_length=30)),
                ("paymentType", models.CharField(default="online", max_length=30)),
                (
                    "totalCost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("status", models.CharField(default="accepted", max_length=10)),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField(max_length=256)),
                (
                    "products",
                    models.ManyToManyField(related_name="orders", to="product.product"),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
    ]
