# Generated by Django 5.1.7 on 2025-04-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(default="accepted", max_length=30),
        ),
    ]
